const models = [
  {
    APLID: "AACHYC",
    Custodian_ID: "GNW",
    StrategistName: "Cash Solutions",
    StrategistCode: "CAS",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 0,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "High Yield Cash",
    ModelSetName: "Cash",
    ModelSetTypeID: 58,
    HardMinimumInvestment: 100000.0,
    SoftMinimumInvestment: 100000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 100.0,
    ApproachId: 6,
    ApproachName: "Additional Investment Solutions",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 480,
    StrategyName: "Cash Solutions",
    StrategistGroupId: 33,
    StrategistGroupName: "Cash Alternative Strategists",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "AACS11",
    Custodian_ID: "GNW",
    StrategistName: "Administrative Account",
    StrategistCode: "ADMN",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 0,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "Custodial Sweep",
    ModelSetName: "Cash",
    ModelSetTypeID: 58,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 100.0,
    ApproachId: 6,
    ApproachName: "Additional Investment Solutions",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 4,
    StrategyName: "Unclassified",
    StrategistGroupId: 4,
    StrategistGroupName: "Administrative Accounts",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "AAGSNM",
    Custodian_ID: "GNW",
    StrategistName: "Administrative Account",
    StrategistCode: "ADMN",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 0,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "General Securities - Non-Managed",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 100.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 100.0,
    ApproachId: 6,
    ApproachName: "Additional Investment Solutions",
    TradingMinimum: 100.0,
    IsSingleTicker: false,
    StrategyId: 4,
    StrategyName: "Unclassified",
    StrategistGroupId: 4,
    StrategistGroupName: "Administrative Accounts",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: true,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "ABSGT6",
    Custodian_ID: "GNW",
    StrategistName: "AllianceBernstein",
    StrategistCode: "ABNEQ",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 6,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "AllianceBernstein Sustainable Global Thematic ADR Portfolio",
    ModelSetName: "Global Active Core",
    ModelSetTypeID: 47,
    HardMinimumInvestment: 100000.0,
    SoftMinimumInvestment: 100000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 100000.0,
    IsSingleTicker: false,
    StrategyId: 543,
    StrategyName: "Sustainable Global Thematic ADR Portfolio",
    StrategistGroupId: 212,
    StrategistGroupName: "AllianceBernstein",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "AIADR6",
    Custodian_ID: "GNW",
    StrategistName: "Acadian Asset Management LLC",
    StrategistCode: "AAMEQ",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 6,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "Acadian International ADR Non-U.S. Equity",
    ModelSetName: "Tactical",
    ModelSetTypeID: 119,
    HardMinimumInvestment: 100000.0,
    SoftMinimumInvestment: 100000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 100.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 2,
    ApproachName: "Tactical Strategies - Enhanced Return Focus",
    TradingMinimum: 100000.0,
    IsSingleTicker: false,
    StrategyId: 536,
    StrategyName: "Tactical",
    StrategistGroupId: 209,
    StrategistGroupName: "Acadian Asset Management LLC",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "AMFBL3",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 3,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Moderate Growth and Income, Profile 3",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFGG6",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 6,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Global Growth, Profile 6",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFGI4",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 4,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Growth and Income, Profile 4",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFGR5",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 5,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Moderate Growth, Profile 5",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFGR6",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 6,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Growth, Profile 6",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFIN2",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 2,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Conservative Growth and Income, Profile 2",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFPR1",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 1,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Preservation, Profile 1",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFRI1",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 1,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Retirement Income - Conservative, Profile 1",
    ModelSetName: "Multi Asset Income",
    ModelSetTypeID: 82,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFRI2",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 2,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Retirement Income - Moderate, Profile 2",
    ModelSetName: "Multi Asset Income",
    ModelSetTypeID: 82,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFRI3",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 3,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Retirement Income - Enhanced, Profile 3",
    ModelSetName: "Multi Asset Income",
    ModelSetTypeID: 82,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFTE1",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 1,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Preservation, Tax-Exempt, Profile 1",
    ModelSetName: "Global Tax-Sensitive",
    ModelSetTypeID: 11,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFTE2",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 2,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Conservative Gr & Inc, Tax-Aware, Profile 2",
    ModelSetName: "Global Tax-Sensitive",
    ModelSetTypeID: 11,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFTE3",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 3,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Moderate Gr & Inc, Tax-Aware, Profile 3",
    ModelSetName: "Global Tax-Sensitive",
    ModelSetTypeID: 11,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "AMFTE4",
    Custodian_ID: "GNW",
    StrategistName: "American Funds",
    StrategistCode: "AMF",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 4,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "American Funds Growth & Income, Tax-Aware, Profile 4",
    ModelSetName: "Global Tax-Sensitive",
    ModelSetTypeID: 11,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 431,
    StrategyName: "Model Portfolios",
    StrategistGroupId: 170,
    StrategistGroupName: "American Funds",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIBS2",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISM",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 2,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "Aris Income Builder, Profile 2, Conservative",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 26,
    StrategyName: "Income Builder",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIBT2",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISM",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 2,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "Aris Income Builder, TS, Profile 2, Conservative",
    ModelSetName: "Global Tax-Sensitive",
    ModelSetTypeID: 11,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 392,
    StrategyName: "Income Builder, Tax Sensitive",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIBU2",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 2,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Asset Builder, Profile 2, Conservative",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 17,
    StrategyName: "Asset Builder",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIBU3",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 3,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Asset Builder, Profile 3 Moderate",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 17,
    StrategyName: "Asset Builder",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIBU5",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 5,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Asset Builder, Profile 5, Growth",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 17,
    StrategyName: "Asset Builder",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIBU6",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 6,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Asset Builder, Profile 6 Maximum Growth",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 17,
    StrategyName: "Asset Builder",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIPV2",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 2,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Personal Values - Faith, Profile 2, Conservative",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 31,
    StrategyName: "Personal Values - Faith",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIPV3",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 3,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Personal Values - Faith, Profile 3, Moderate",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 31,
    StrategyName: "Personal Values - Faith",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIPV5",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 5,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Personal Values - Faith, Profile 5, Growth",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 31,
    StrategyName: "Personal Values - Faith",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARIPV6",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 6,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Personal Values - Faith, Profile 6, Maximum Growth",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 31,
    StrategyName: "Personal Values - Faith",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARISC1",
    Custodian_ID: "GNW",
    StrategistName: "Aris HNW",
    StrategistCode: "ARIS",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 1,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "Aris Custom High Net Worth, Profile 1, Conservative ",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 450000.0,
    SoftMinimumInvestment: 500000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 10000.0,
    IsSingleTicker: false,
    StrategyId: 20,
    StrategyName: "Custom Portfolio",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "ARISC2",
    Custodian_ID: "GNW",
    StrategistName: "Aris HNW",
    StrategistCode: "ARIS",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 2,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "Aris Custom High Net Worth, Profile 2, Moderate Conservative",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 450000.0,
    SoftMinimumInvestment: 500000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 20,
    StrategyName: "Custom Portfolio",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "ARISC3",
    Custodian_ID: "GNW",
    StrategistName: "Aris HNW",
    StrategistCode: "ARIS",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 3,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "Aris Custom High Net Worth, Profile 3, Moderate",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 450000.0,
    SoftMinimumInvestment: 500000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 20,
    StrategyName: "Custom Portfolio",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "ARISC4",
    Custodian_ID: "GNW",
    StrategistName: "Aris HNW",
    StrategistCode: "ARIS",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 4,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "Aris Custom High Net Worth, Profile 4, Moderate Growth",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 450000.0,
    SoftMinimumInvestment: 500000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 10000.0,
    IsSingleTicker: false,
    StrategyId: 20,
    StrategyName: "Custom Portfolio",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "ARISC5",
    Custodian_ID: "GNW",
    StrategistName: "Aris HNW",
    StrategistCode: "ARIS",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 5,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "Aris Custom High Net Worth, Profile 5, Growth",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 450000.0,
    SoftMinimumInvestment: 500000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 20,
    StrategyName: "Custom Portfolio",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "ARISC6",
    Custodian_ID: "GNW",
    StrategistName: "Aris HNW",
    StrategistCode: "ARIS",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 6,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "Aris Custom High Net Worth, Profile 6, Maximum Growth",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 450000.0,
    SoftMinimumInvestment: 500000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 20,
    StrategyName: "Custom Portfolio",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "ARISP2",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 2,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Personal Values - Social, Profile 2, Conservative",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 33,
    StrategyName: "Socially Responsible",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARISP3",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 3,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Personal Values - Social, Profile 3, Moderate",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 33,
    StrategyName: "Socially Responsible",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARISP5",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 5,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Personal Values - Social, Profile 5, Growth",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 33,
    StrategyName: "Socially Responsible",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARISP6",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 6,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Personal Values - Social, Profile 6, Maximum Growth",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 33,
    StrategyName: "Socially Responsible",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARITS2",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 2,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Asset Builder, TS, Profile 2, Conservative ",
    ModelSetName: "Global Tax-Sensitive",
    ModelSetTypeID: 11,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 18,
    StrategyName: "Asset Builder, Tax Sensitive",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARITS3",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 3,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Asset Builder, TS, Profile 3, Moderate",
    ModelSetName: "Global Tax-Sensitive",
    ModelSetTypeID: 11,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 18,
    StrategyName: "Asset Builder, Tax Sensitive",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARITS5",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 5,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Asset Builder, TS, Profile 5, Growth",
    ModelSetName: "Global Tax-Sensitive",
    ModelSetTypeID: 11,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 18,
    StrategyName: "Asset Builder, Tax Sensitive",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ARITS6",
    Custodian_ID: "GNW",
    StrategistName: "Aris",
    StrategistCode: "ARISI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 6,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "Aris Asset Builder, TS, Profile 6, Max Growth",
    ModelSetName: "Global Tax-Sensitive",
    ModelSetTypeID: 11,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 18,
    StrategyName: "Asset Builder, Tax Sensitive",
    StrategistGroupId: 15,
    StrategistGroupName: "Aris",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ASTDS1",
    Custodian_ID: "GNW",
    StrategistName: "AssetMark",
    StrategistCode: "DAS",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 1,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "AssetMark WealthBuilder, Profile 1",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 446,
    StrategyName: "DAS Core Portfolio",
    StrategistGroupId: 16,
    StrategistGroupName: "AssetMark",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ASTDS2",
    Custodian_ID: "GNW",
    StrategistName: "AssetMark",
    StrategistCode: "DAS",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 2,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "AssetMark WealthBuilder, Profile 2",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 446,
    StrategyName: "DAS Core Portfolio",
    StrategistGroupId: 16,
    StrategistGroupName: "AssetMark",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ASTDS3",
    Custodian_ID: "GNW",
    StrategistName: "AssetMark",
    StrategistCode: "DAS",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 3,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "AssetMark WealthBuilder, Profile 3",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 446,
    StrategyName: "DAS Core Portfolio",
    StrategistGroupId: 16,
    StrategistGroupName: "AssetMark",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ASTDS4",
    Custodian_ID: "GNW",
    StrategistName: "AssetMark",
    StrategistCode: "DAS",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 4,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "AssetMark WealthBuilder, Profile 4",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 446,
    StrategyName: "DAS Core Portfolio",
    StrategistGroupId: 16,
    StrategistGroupName: "AssetMark",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ASTDS5",
    Custodian_ID: "GNW",
    StrategistName: "AssetMark",
    StrategistCode: "DAS",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 5,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "AssetMark WealthBuilder, Profile 5",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 446,
    StrategyName: "DAS Core Portfolio",
    StrategistGroupId: 16,
    StrategistGroupName: "AssetMark",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ASTDS6",
    Custodian_ID: "GNW",
    StrategistName: "AssetMark",
    StrategistCode: "DAS",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 6,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "AssetMark WealthBuilder, Profile 6",
    ModelSetName: "Unclassified",
    ModelSetTypeID: 13,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 446,
    StrategyName: "DAS Core Portfolio",
    StrategistGroupId: 16,
    StrategistGroupName: "AssetMark",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "ASXAM5",
    Custodian_ID: "GNW",
    StrategistName: "AlphaSimplex",
    StrategistCode: "ASXI",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 5,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "AlphaSimplex, Alternative Model Portfolio, Profile 5, Growth",
    ModelSetName: "Global Standard",
    ModelSetTypeID: 10,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 100.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 4,
    ApproachName: "Diversifying Strategies - Equity Alternatives",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 8,
    StrategyName: "Risk Efficient Alternatives",
    StrategistGroupId: 8,
    StrategistGroupName: "AlphaSimplex",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BALCS6",
    Custodian_ID: "GNW",
    StrategistName: "Brown Advisory",
    StrategistCode: "BAYEQ",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 6,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "Brown Advisory Large-Cap Sustainable Growth",
    ModelSetName: "Domestic",
    ModelSetTypeID: 33,
    HardMinimumInvestment: 100000.0,
    SoftMinimumInvestment: 100000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 100.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 2,
    ApproachName: "Tactical Strategies - Enhanced Return Focus",
    TradingMinimum: 100000.0,
    IsSingleTicker: false,
    StrategyId: 544,
    StrategyName: " Large-Cap Sustainable Growth",
    StrategistGroupId: 213,
    StrategistGroupName: "Brown Advisory",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "BCM1DC",
    Custodian_ID: "GNW",
    StrategistName: "Beaumont Capital Management",
    StrategistCode: "BCM",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 1,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "Beaumont Capital Management, Profile 1, Conservative",
    ModelSetName: "Decathlon",
    ModelSetTypeID: 107,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 100.0,
    Allocation_Additional: 0.0,
    ApproachId: 5,
    ApproachName: "Diversifying Strategies - Bonds and Bond Alternatives",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 52,
    StrategyName: "Decathlon Aspect - Conservative",
    StrategistGroupId: 21,
    StrategistGroupName: "Beaumont",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BCM3DC",
    Custodian_ID: "GNW",
    StrategistName: "Beaumont Capital Management",
    StrategistCode: "BCM",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 3,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "Beaumont Capital Management, Profile 3, Moderate",
    ModelSetName: "Decathlon",
    ModelSetTypeID: 107,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 100.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 2,
    ApproachName: "Tactical Strategies - Enhanced Return Focus",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 53,
    StrategyName: "Decathlon Aspect",
    StrategistGroupId: 21,
    StrategistGroupName: "Beaumont",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BCM5DC",
    Custodian_ID: "GNW",
    StrategistName: "Beaumont Capital Management",
    StrategistCode: "BCM",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 5,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "Beaumont Capital Management, Profile 5, Growth",
    ModelSetName: "Decathlon",
    ModelSetTypeID: 107,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 100.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 2,
    ApproachName: "Tactical Strategies - Enhanced Return Focus",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 53,
    StrategyName: "Decathlon Aspect",
    StrategistGroupId: 21,
    StrategistGroupName: "Beaumont",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKAR1",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 1,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock, Risk Focused Income, Profile 1, Conservative",
    ModelSetName: "Risk Focused Income",
    ModelSetTypeID: 106,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 100.0,
    Allocation_Additional: 0.0,
    ApproachId: 5,
    ApproachName: "Diversifying Strategies - Bonds and Bond Alternatives",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 56,
    StrategyName: "Risk Focused Income",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKED6",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock",
    StrategistCode: "BLKEQ",
    ProgramGroupLongName: "Privately Managed Accounts",
    ProfileID: 6,
    Program_ID: "IMA",
    ProgramName: "Individually Managed Accounts",
    ModelName: "BlackRock Equity Dividend",
    ModelSetName: "Tactical",
    ModelSetTypeID: 119,
    HardMinimumInvestment: 100000.0,
    SoftMinimumInvestment: 100000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 100.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 2,
    ApproachName: "Tactical Strategies - Enhanced Return Focus",
    TradingMinimum: 95000.0,
    IsSingleTicker: false,
    StrategyId: 535,
    StrategyName: "Tactical",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: false,
  },
  {
    APLID: "BLKES2",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 2,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock Target Allocation ESG Models Profile 2",
    ModelSetName: "Blended Core",
    ModelSetTypeID: 23,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 541,
    StrategyName: "Target Allocation ESG Models",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKES3",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 3,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock Target Allocation ESG Models Profile 3",
    ModelSetName: "Blended Core",
    ModelSetTypeID: 23,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 541,
    StrategyName: "Target Allocation ESG Models",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKES4",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 4,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock Target Allocation ESG Models, Profile 4",
    ModelSetName: "Blended Core",
    ModelSetTypeID: 23,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 541,
    StrategyName: "Target Allocation ESG Models",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKES6",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 6,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock Target Allocation ESG Models, Profile 6",
    ModelSetName: "Blended Core",
    ModelSetTypeID: 23,
    HardMinimumInvestment: 9000.0,
    SoftMinimumInvestment: 10000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 541,
    StrategyName: "Target Allocation ESG Models",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKMA3",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 2,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock, MAI, Profile 2, Moderate Conservative",
    ModelSetName: "Multi Asset Income",
    ModelSetTypeID: 82,
    HardMinimumInvestment: 22500.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 55,
    StrategyName: "Multi-Asset Income",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTM1",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 1,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock Target Allocation Multi-Manager w Alts Profile 1",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 545,
    StrategyName: "Target Allocation Multi-Manager with Alternatives",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTM2",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 2,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock Target Allocation Multi-Manager w Alts Profile 2",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 545,
    StrategyName: "Target Allocation Multi-Manager with Alternatives",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTM3",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 3,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock Target Allocation Multi-Manager w Alts Profile 3",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 545,
    StrategyName: "Target Allocation Multi-Manager with Alternatives",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTM4",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 4,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock Target Allocation Multi-Manager w Alts Profile 4",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 545,
    StrategyName: "Target Allocation Multi-Manager with Alternatives",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTM6",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 6,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock Target Allocation Multi-Manager w Alts Profile 6",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 545,
    StrategyName: "Target Allocation Multi-Manager with Alternatives",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTT1",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 1,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock TA Multi-Manager w Alts Tax Aware Profile 1",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 546,
    StrategyName: "Target Allocation Multi-Manager with Alternatives Tax Aware",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTT2",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 2,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock TA Multi-Manager w Alts Tax Aware Profile 2",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 546,
    StrategyName: "Target Allocation Multi-Manager with Alternatives Tax Aware",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTT3",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 3,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock TA Multi-Manager w Alts Tax Aware Profile 3",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 546,
    StrategyName: "Target Allocation Multi-Manager with Alternatives Tax Aware",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTT4",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 4,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock TA Multi-Manager w Alts Tax Aware Profile 4",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 546,
    StrategyName: "Target Allocation Multi-Manager with Alternatives Tax Aware",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLKTT6",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLKETF",
    ProgramGroupLongName: "Exchange Traded Funds",
    ProfileID: 6,
    Program_ID: "ETF",
    ProgramName: "Exchange Traded Funds",
    ModelName: "BlackRock TA Multi-Manager w Alts Tax Aware Profile 6",
    ModelSetName: "Core Markets",
    ModelSetTypeID: 120,
    HardMinimumInvestment: 24000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 100.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 0.0,
    Allocation_Additional: 0.0,
    ApproachId: 1,
    ApproachName: "Core Markets",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 546,
    StrategyName: "Target Allocation Multi-Manager with Alternatives Tax Aware",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
  {
    APLID: "BLROAS",
    Custodian_ID: "GNW",
    StrategistName: "BlackRock Financial Management, Inc.",
    StrategistCode: "BLK",
    ProgramGroupLongName: "Mutual Funds",
    ProfileID: 2,
    Program_ID: "MF",
    ProgramName: "Mutual Funds",
    ModelName: "BlackRock Opportunistic Alternatives",
    ModelSetName: "Diversified Alternatives",
    ModelSetTypeID: 102,
    HardMinimumInvestment: 10000.0,
    SoftMinimumInvestment: 25000.0,
    ProductTypeEv: 1,
    SingleStrategyAvailable: true,
    CustomGPSSelectAvailable: false,
    MultipleStrategyAvailable: false,
    Allocation_Core: 0.0,
    Allocation_TacticalEnhanced: 0.0,
    Allocation_TacticalLimit: 0.0,
    Allocation_DiversifyingEquity: 0.0,
    Allocation_DiversifyingBond: 100.0,
    Allocation_Additional: 0.0,
    ApproachId: 5,
    ApproachName: "Diversifying Strategies - Bonds and Bond Alternatives",
    TradingMinimum: 1000.0,
    IsSingleTicker: false,
    StrategyId: 54,
    StrategyName: "Unclassified",
    StrategistGroupId: 22,
    StrategistGroupName: "BlackRock",
    IsOptionsEligible: false,
    HideFromICT: false,
    IncludeInICTforSoftClosures: false,
    SPPCustomAvailable: false,
    SleeveClassificationCode: null,
    SavosTaxRegistration: true,
    IsGeneralSecurities: false,
    TaxManagementEligibleRegistration: true,
    TaxManagementEligibleModel: true,
  },
];

export default models;
